[package]
name = "RustOpenGLSDL2"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = {version =  "*", features = ["bundled"]  }
gl = { path = "lib/gl" }
image = "0.23"
nalgebra = "0.29"

[build-dependencies]
walkdir = "2.1"
